// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Universtiy_Portal.Data;

#nullable disable

namespace Universtiy_Portal.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220507074452_AddedDetails")]
    partial class AddedDetails
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Universtiy_Portal.Data.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Passward")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Universtiy_Portal.Data.College", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colleges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "College of Free Education"
                        },
                        new
                        {
                            Id = 2,
                            Name = "College of Freedom"
                        });
                });

            modelBuilder.Entity("Universtiy_Portal.Data.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CollegeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CollegeId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Karvenagar",
                            CollegeId = 1,
                            Name = "Avinash",
                            Password = "2233AAA",
                            UserName = "Avi@111"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Karvenagar",
                            CollegeId = 2,
                            Name = "Swarup",
                            Password = "2233AAA",
                            UserName = "swa@111"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Karvenagar",
                            CollegeId = 1,
                            Name = "motya",
                            Password = "2233AAA",
                            UserName = "mot@111"
                        });
                });

            modelBuilder.Entity("Universtiy_Portal.Data.Student", b =>
                {
                    b.HasOne("Universtiy_Portal.Data.College", "college")
                        .WithMany()
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("college");
                });
#pragma warning restore 612, 618
        }
    }
}
